[package]
name = "kernel-alloc"
version = "0.1.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
customizable-buddy = "0.0.3"
page-table = "0.0.6"
